#!/usr/bin/env bash

# This script configures a new Ubuntu machine to add a custom HTTP response header to Nginx.

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add custom HTTP header configuration
echo "add_header X-Served-By \$hostname;" | sudo tee /etc/nginx/conf.d/custom_http_response_header.conf

# Test configuration
sudo nginx -t

# Reload Nginx
sudo systemctl reload nginx
