#!/usr/bin/env bash

# Transfer a file from a client to a server
if [[ $# -lt 4 ]]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit
fi

path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"
scp -i "$path_to_ssh_key" -o StrictHostKeyChecking=No "$path_to_file" "$username@$ip":~/
