#!/usr/bin/env bash
# a Bash script that sets up Nginx on a server.

sudo apt update
sudo apt install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html

echo "Holberton School" >> /etc/nginx/html/index.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
"> /etc/nginx/sites-available/default

sudo service nginx restart
