#!/usr/bin/env bash
# Update package lists and upgrade system packages
sudo apt-get update
sudo apt-get upgrade -y

# Install Nginx web server
sudo apt-get install nginx -y

# Set Nginx to listen on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Create a HTML file containing "Holberton School"
echo "Holberton School" | sudo tee /var/www/html/index.html

# Configure Nginx to serve the HTML file as the default page
sudo sed -i '/index/s/index.html/index.html index.htm/g' /etc/nginx/sites-available/default
sudo systemctl restart nginx
