#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx

echo "301 moved permanently" > /usr/share/nginx/html/custom_301.html
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html/;
    error_page 301 /custom_301.html;
    location /redirect_me {
        return 301 /usr/share/nginx/html/custom_301.html;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
